# Name of the created jar file
project_name: tweetotbix

# Directory to create and place produced project files in
output_dir: package

# File to set as main-class in jar manifest
main_java_file: org.rubyforge.rawr.Main

# Ruby file to invoke when jar is started
main_ruby_file: main

# Location of Ruby source files
ruby_source_dir: src

# Location of Ruby library files
ruby_library_dir: lib/ruby

# Location of Java source files
java_source_dir: src

# Directories that should have ALL their .jar contents loaded on the classpath
# If you wish to only include specific jars from a directory use classpath_files
classpath_dirs:
   - lib/java

# Individual files that should be loaded on the classpath
classpath_files:
   - lib/java/jruby-complete.jar
   - lib/java/swing-layout-1.0.3.jar

# Directory that should be loaded onto the java.library.path 
#native_library_dirs:
#    - lib/java/native

# Directories which you want the coentents of to be copied to the output directory
#package_data_dirs:
#    - lib

# Directories to be added into the jar
#jar_data_dirs:
#    - data

# jar signing values for JNLP bundling.  If you are using a self-signed jar, 
# uncomment the following lines and edit the password.  
# web_start: 
#    self_sign: true
#    self_sign_passphrase: some_password

# JNLP file configuration values.   Uncomment rhe following and edit with your own details
# jnlp:
#    title: Edit your title
#    vendor: Edit your vendor name
#    codebase: http://edit.your.codebase.url
#    homepage_href:  edit.your.homepage
#    description: "Edit your description"
#    offline_allowed: true
#    shortcut_desktop:  true
#    menu_submenu:  Edit your menu sub-menu

#  Java 'keytool' response values.  Uncomment and edit these values if you
#  want to use the 'rawr:keytool' task
# keytool_responses:
#    password: SekritPassword
#    first_and_last_name: Ilya Kuryakin
#    organization: U.N.C.L.E.
#    locality: NYC
#    state_or_province: NY
#    country_code: US

# NOT YET IMPLEMENTED
#pre_processing_task:
#post_processing_task:
